import_history:
  fields:
    entry_id:
      required: false
      selector:
        config_entry:
          integration: soregies
    months:
      required: false
      selector:
        number:
          min: 1
          max: 120
          step: 1
          mode: box
          unit_of_measurement: mois
